apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${namespace}
helmCharts:
- name: gha-runner-scale-set
  namespace: ${namespace}
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  version: 0.12.1
  releaseName: arc-runner-set
  includeCRDs: false
  valuesFile: values.yaml

resources:
  - namespace.yaml
